version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: notes_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d  # auto-run init.sql on first startup

  web:
    build: .
    container_name: notes_web
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      - FLASK_ENV=development

volumes:
  db_data:

